version: '3.7'

volumes:
    postgres_data:
    static:
    media:

services:
    db:
        image: postgres:12.4
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    web:
        image: khelskelly/foodgram
        restart: unless-stopped
        volumes:
            - static:/foodgram/static/
            - media:/foodgram/media/
        expose:
            - '8000'
        depends_on:
            - db
        env_file:
            - ./.env
    nginx:
        image: nginx:1.19.3
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static:/var/html/static/
            - media:/var/html/media/
        depends_on:
            - web
