# Generated by Django 3.2.4 on 2021-06-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210608_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True),
        ),
    ]
